name: CI/CD - Docker Build & Deploy

on:
  push:
    branches:
      - test  # O la rama que estés utilizando

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Login en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Microservice GraphQL
        run: |
            echo "Building and pushing microservices_graphql..."
            docker build -f Microservices-graphql/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/microservices_graphql:latest Microservices-graphql
            docker push ${{ secrets.DOCKER_USERNAME }}/microservices_graphql:latest
        
      - name: Build and Push Microservice_create_vaccine_card
        run: |
          echo "Building and pushing Microservice_create_vaccine_card"
          docker build -f vaccine_card_management/Microservice_create_vaccine_card/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/microservice_create_vaccine_card:latest vaccine_card_management/Microservice_create_vaccine_card
          docker push ${{ secrets.DOCKER_USERNAME }}/microservice_create_vaccine_card:latest

      - name: Build and Push Microservice_vaccine_card
        run: |
          echo "Building and pushing Microservice_vaccine_card"
          docker build -f vaccine_card_management/Microservice_vaccine_card/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/microservice_vaccine_card:latest vaccine_card_management/Microservice_vaccine_card
          
      - name: Build and Push Microservice Owner List
        run: |
              echo "Building and pushing microservice_list_owner..."
              docker build -f owner_management/Microservice_list_owner/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/microservice_list_owner:latest owner_management/Microservice_list_owner
              docker push ${{ secrets.DOCKER_USERNAME }}/microservice_list_owner:latest
          